name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ['bug🐞']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before you submit a bug report, please run shiba2sashimi with `--verbose` to get more detailed logs.

  - type: textarea
    id: description
    attributes:
      label: '📋 Description'
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: input
    id: shiba2sashimi_version
    attributes:
      label: '🔖 shiba2sashimi Version'
      description: 'Required: Specify the shiba2sashimi version you are using. You can find this information in the `shiba2sashimi -h` command.'
      placeholder: 'e.g., v0.1.0'
    validations:
      required: true

  - type: textarea
    attributes:
      label: '💬 Current Behavior'
      description: |
        Optional: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: '🎯 Expected Behavior'
      description: |
        Optional: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: '⚠️ Error message'
      description: |
        Optional: If applicable, add the error message here.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: '🔍 Environment'
      description: |
          Optional: The environment information.
          Example:
          OS: WSL (Ubuntu 22.04)
          Python: 3.9.7
      value: |
          OS:
          Python:
      render: markdown
    validations:
      required: false

  - type: textarea
    id: anything_else
    attributes:
      label: '📎 Anything else?'
      description: |
        Optional: Add any other contexts, links, or screenshots about the bug here.
    validations:
      required: false
